-- En este archivo deben estar tus ejercicios de consultas sql
-- 1. 
SELECT e.NOMBRES 
FROM EMPLEADOS e 
ORDER BY e.NOMBRES DESC

--2
SELECT e.NOMBRES, p.PUESTO, l.LOCALIDAD 
FROM EMPLEADOS e
JOIN DEPARTAMENTOS d ON d.ID = e.DEPARTAMENTO_ID
JOIN LOCALIDADES l ON l.ID = d.LOCALIDAD_ID
JOIN PUESTOS p ON p.ID = e.PUESTO_ID
WHERE p.PUESTO = "Soporte";

--3
SELECT e.NOMBRES 
FROM EMPLEADOS e 
WHERE e.NOMBRES LIKE '%o';

--4
SELECT e.NOMBRES, e.SUELDO, l.LOCALIDAD 
FROM EMPLEADOS e
JOIN DEPARTAMENTOS d ON d.ID = e.DEPARTAMENTO_ID
JOIN LOCALIDADES l ON l.ID = d.LOCALIDAD_ID
WHERE l.LOCALIDAD = "Carlos Paz";

--5
SELECT e.NOMBRES, e.SUELDO, l.LOCALIDAD 
FROM EMPLEADOS e
JOIN DEPARTAMENTOS d ON d.ID = e.DEPARTAMENTO_ID
JOIN LOCALIDADES l ON l.ID = d.LOCALIDAD_ID
WHERE e.SUELDO BETWEEN 10000 AND 13000;

--6
SELECT d.DENOMINACION, COUNT(e.ID) AS empleado_cuenta
FROM EMPLEADOS e 
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
GROUP BY d.DENOMINACION 
HAVING COUNT(e.ID) > 5;

--7
SELECT e.NOMBRES 
FROM EMPLEADOS e 
JOIN PUESTOS p ON e.PUESTO_ID = p.ID
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
WHERE d.DENOMINACION = "Córdoba" 
AND (p.PUESTO = "Analista" OR p.PUESTO = "Programador");

--8
SELECT AVG(SUELDO) AS sueldo_medio 
FROM EMPLEADOS e;

--9
SELECT MAX(e.SUELDO) AS maximo_sueldo 
FROM EMPLEADOS e
JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID
WHERE d.ID = 10;

--10
SELECT MIN(SUELDO) AS sueldo_minimo 
FROM EMPLEADOS e
JOIN PUESTOS p ON e.PUESTO_ID = p.ID
WHERE p.PUESTO = "Soporte";

--11
SELECT p.PUESTO, SUM(e.SUELDO) AS sueldo_puesto 
FROM EMPLEADOS e
JOIN PUESTOS p ON e.PUESTO_ID = p.ID 
GROUP BY p.PUESTO;